In [1]:
# Importazione delle librerie necessarie

import os
import librosa
import numpy as np
import pandas as pd

In [2]:
# Montaggio di Google Drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Caricamento delle etichette delle emozioni

dataset_path = '/content/drive/MyDrive/ABEC/DATASET'
emotion_labels = sorted(os.listdir(dataset_path))
print(emotion_labels)

['ANGER', 'DISGUST', 'FEAR', 'HAPPINESS', 'NEUTRALITY', 'SADNESS']

In [4]:
# Caricamento dei files

paths = []
labels = []
for emotion in emotion_labels:
  emotion_path = os.listdir(os.path.join(dataset_path, emotion))
  for filename in emotion_path:
    paths.append(os.path.join(dataset_path, emotion, filename))
    labels.append(emotion)
print('Dataset caricato')

Dataset caricato

In [5]:
# Creazione del DataFrame

df = pd.DataFrame()
df['path'] = paths
df['label'] = labels
df.head()

                                                path  label
0  /content/drive/MyDrive/ABEC/DATASET/ANGER/1020...  ANGER
1  /content/drive/MyDrive/ABEC/DATASET/ANGER/1020...  ANGER
2  /content/drive/MyDrive/ABEC/DATASET/ANGER/1020...  ANGER
3  /content/drive/MyDrive/ABEC/DATASET/ANGER/1020...  ANGER
4  /content/drive/MyDrive/ABEC/DATASET/ANGER/1020...  ANGER

In [6]:
# Funzioni per l'estrazione delle features

def extract_mfcc(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  mfcc = np.mean(librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40).T, axis=0)
  return mfcc

def extract_chromagram(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  chroma = np.mean(librosa.feature.chroma_stft(y=y, sr=sr), axis=1)
  return chroma

def extract_melspectrogram(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  mel = np.mean(librosa.feature.melspectrogram(y=y, sr=sr), axis=1)
  return mel

def extract_tonnetz(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(y), sr=sr), axis=1)
  return tonnetz

def extract_spectral_contrast(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  spectral_contrast = np.mean(librosa.feature.spectral_contrast(y=y, sr=sr), axis=1)
  return spectral_contrast

def extract_zero_crossing_rate(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  zcr = np.mean(librosa.feature.zero_crossing_rate(y=y), axis=1)
  return zcr

def extract_hnr(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  harmonics = librosa.effects.harmonic(y)
  noise = y - harmonics
  hnr = np.sum(harmonics**2) / np.sum(noise**2 + 1e-10)
  return hnr

def extract_teager_energy_operator(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  teo = np.mean(librosa.feature.rms(y=y), axis=1)
  return teo

def extract_short_term_energy(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  ste = np.mean(librosa.feature.rms(y=y), axis=1)
  return ste

def extract_power_spectral_density(filename):
  y, sr = librosa.load(filename, duration=3, offset=0.5)
  psd_abs = np.abs(np.fft.fft(y)) ** 2
  psd = np.mean(psd_abs)
  return psd

In [7]:
# Estrazione della feature: MFCC

df['mfcc'] = df['path'].apply(lambda x: extract_mfcc(x))

In [8]:
# Estrazione della feature: CHROMAGRAM

df['chroma'] = df['path'].apply(lambda x: extract_chromagram(x))

/usr/local/lib/python3.10/dist-packages/librosa/core/pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(

In [9]:
# Estrazione della feature: MEL-SCALE SPECTOGRAM

df['mel'] = df['path'].apply(lambda x: extract_melspectrogram(x))

In [10]:
# Estrazione della feature: TONNETZ REPRESENTATION

df['tonnetz'] = df['path'].apply(lambda x: extract_tonnetz(x))

/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=759
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=794
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=840
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=828
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=817
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=679
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=863
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=713
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=932
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=725
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=989
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=851
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=690
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=748
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=898
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=449
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=771
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=909
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=943
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=667
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=920
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=472
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=852
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=426
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=529
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=598
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=610
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=564
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=495
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=541
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=575
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=633
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=874
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=518
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=587
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=575
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=920
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=612
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=736
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=875
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=438
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=552
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=679
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=564
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=541
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=1012
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=506
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=610
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=713
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=656
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=621
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=759
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=828
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=840
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=932
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=886
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=955
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=529
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=966
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=829
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=415
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=805
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=851
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=989
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=495
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=725
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=702
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=714
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=357
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=943
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=472
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=633
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=909
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=748
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=690
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=794
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=817
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=863
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=644
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=667
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=483
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=782
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=771
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=1001
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=874
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=852
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=426
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=897
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=921
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=461
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=615
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=898
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=449
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=806
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=403
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=944
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=598
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=760
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=380
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=737
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=369
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=783
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=392
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=691
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=346
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=976
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=645
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=323
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=668
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=334
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=576
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=288
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=530
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=265
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=622
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=311
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=599
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=300
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=651
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=1024 is too large for input signal of length=980
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(

In [11]:
# Estrazione della feature: SPECTRAL CONTRAST

df['spectral_contrast'] = df['path'].apply(lambda x: extract_spectral_contrast(x))

In [12]:
# Stampa delle prime 5 righe del DataFrame di base con le features estratte

df.head()

,path,label,mfcc,chroma,mel,tonnetz,spectral_contrast
0,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-346.29526, 137.64049, 8.69169, 35.311882, -9...","[0.29201826, 0.38502562, 0.29120973, 0.3123079...","[0.07737846, 0.034783144, 0.04425149, 0.062268...","[-0.0430883237494016, -0.05187423004202757, -0...","[13.31842625645253, 16.873059068316007, 20.454..."
1,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-345.26352, 137.31744, 37.12389, 19.821321, -...","[0.25346315, 0.4409166, 0.39678228, 0.2390734,...","[0.05265753, 0.043628313, 0.04868232, 0.091114...","[-0.05439641105154431, -0.023526455819770774, ...","[14.453045085379497, 15.449812085063297, 19.91..."
2,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-335.2242, 107.78316, 16.172033, 40.845966, 4...","[0.26270318, 0.34137246, 0.33419836, 0.3078067...","[0.070515454, 0.039977632, 0.04855162, 0.08995...","[-0.0032069529342134808, 0.0006316686876027121...","[13.717498757184677, 15.727700609652093, 18.98..."
3,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-350.34436, 126.87104, 24.150877, 50.20368, -...","[0.29323444, 0.4240524, 0.3292996, 0.20072058,...","[0.05762726, 0.036191218, 0.05052052, 0.065974...","[-0.06355210503470457, 0.02546927699985149, -0...","[14.595053701083883, 16.01931479753035, 20.898..."
4,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-353.60526, 106.025505, 10.934089, 50.296932,...","[0.20039691, 0.2804537, 0.24138005, 0.19346811...","[0.08442482, 0.037809636, 0.039918914, 0.07282...","[0.019575719295071896, -0.01390564029447752, -...","[12.210900862136034, 14.34903031625579, 20.344..."

In [13]:
# Salvataggio del DataFrame di base attraverso l'utilizzo di Pickle

df.to_pickle('Base.pkl')

In [14]:
# Estrazione della feature: ZERO-CROSSING RATE

df['zero_crossing'] = df['path'].apply(lambda x: extract_zero_crossing_rate(x))

In [15]:
# Estrazione della feature: HARMONICS-TO-NOISE RATIO

df['hnr'] = df['path'].apply(lambda x: extract_hnr(x))

In [16]:
# Estrazione della feature: TEAGER ENERGY OPERATOR

df['teo'] = df['path'].apply(lambda x: extract_teager_energy_operator(x))

In [17]:
# Estrazione della feature: SHORT-TERM ENERGY

df['ste'] = df['path'].apply(lambda x: extract_short_term_energy(x))

In [18]:
# Estrazione della feature: POWER SPECTRAL DENSITY

df['psd'] = df['path'].apply(lambda x: extract_power_spectral_density(x))

In [19]:
# Stampa delle prime 5 righe del DataFrame totale con le features estratte

df.head()

,path,label,mfcc,chroma,mel,tonnetz,spectral_contrast,zero_crossing,hnr,teo,ste,psd
0,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-346.29526, 137.64049, 8.69169, 35.311882, -9...","[0.29201826, 0.38502562, 0.29120973, 0.3123079...","[0.07737846, 0.034783144, 0.04425149, 0.062268...","[-0.0430883237494016, -0.05187423004202757, -0...","[13.31842625645253, 16.873059068316007, 20.454...",[0.06904810855263158],4.752542,[0.037368394],[0.037368394],118.536977
1,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-345.26352, 137.31744, 37.12389, 19.821321, -...","[0.25346315, 0.4409166, 0.39678228, 0.2390734,...","[0.05265753, 0.043628313, 0.04868232, 0.091114...","[-0.05439641105154431, -0.023526455819770774, ...","[14.453045085379497, 15.449812085063297, 19.91...",[0.050478515625],0.563440,[0.04862642],[0.04862642],243.029713
2,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-335.2242, 107.78316, 16.172033, 40.845966, 4...","[0.26270318, 0.34137246, 0.33419836, 0.3078067...","[0.070515454, 0.039977632, 0.04855162, 0.08995...","[-0.0032069529342134808, 0.0006316686876027121...","[13.717498757184677, 15.727700609652093, 18.98...",[0.087744140625],0.154444,[0.034368128],[0.034368128],210.612524
3,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-350.34436, 126.87104, 24.150877, 50.20368, -...","[0.29323444, 0.4240524, 0.3292996, 0.20072058,...","[0.05762726, 0.036191218, 0.05052052, 0.065974...","[-0.06355210503470457, 0.02546927699985149, -0...","[14.595053701083883, 16.01931479753035, 20.898...",[0.065625],1.284537,[0.037899625],[0.037899625],132.283413
4,/content/drive/MyDrive/ABEC/DATASET/ANGER/1020...,ANGER,"[-353.60526, 106.025505, 10.934089, 50.296932,...","[0.20039691, 0.2804537, 0.24138005, 0.19346811...","[0.08442482, 0.037809636, 0.039918914, 0.07282...","[0.019575719295071896, -0.01390564029447752, -...","[12.210900862136034, 14.34903031625579, 20.344...",[0.13329139122596154],0.221793,[0.026042031],[0.026042031],79.418289

In [20]:
# Salvataggio del DataFrame totale attraverso l'utilizzo di Pickle

df.to_pickle('Totale.pkl')